# Generated by Django 4.2.7 on 2023-11-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Persons',
            },
        ),
    ]
