# Generated by Django 4.2.7 on 2023-11-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnedPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BurnedPeople',
            },
        ),
    ]
