# Generated by Django 4.2.7 on 2023-11-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_burnedpeople_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnedpeople',
            name='Commit',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='burnedpeople',
            name='Crunch',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='burnedpeople',
            name='Message',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='burnedpeople',
            name='Task',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
