# Generated by Django 4.2.7 on 2023-11-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_burnedpeople_commit_burnedpeople_crunch_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='date',
            table='main_date',
        ),
    ]
