# Generated by Django 4.2.7 on 2023-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_date_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnedpeople',
            name='BurnChance',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='burnedpeople',
            name='LastName',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='burnedpeople',
            name='Name',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
